import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import { Suspense } from "react";
const inter = Inter({ subsets: ["latin"] });
// Create a client

export const metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <Header />
        {/* <Suspense fallback={<h1 className="text-white">Loading...</h1>}> */}
        {children}
        {/* </Suspense> */}
      </body>
    </html>
  );
}
